# Generated by Django 4.0.3 on 2022-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
